name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd Phonebook-v2
          npm install --production

      - name: Build project
        run: |
          cd Phonebook-v2
           npx tsc -b
           npx vite build
          

      - name: Deploy to nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo mv dist phonebook-build
          sudo cp -r phonebook-build/* /var/www/html/
          sudo systemctl restart nginx
