name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: Phonebook-v2   # 👈 sets default folder for all "run" commands

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to nginxx
        run: |
          sudo rm -rf /var/www/html/phonebook-build
          mv dist phonebook-build
          sudo mv phonebook-build /var/www/html/
          sudo systemctl restart nginx
